stations_dict = {'JOURNAL SQUARE': 'none', 
 '7 AV': 'none',
 '1 AV': 'none',
 'GROVE STREET': 'none',
 'NEWARK BM BW': 'none',
 '96 ST-2 AVE': 'none',
 '46 ST BLISS ST': 'none',
 '34 ST-PENN STA': '34th St - Penn Station',
 '34 ST-HERALD SQ': 'Herald Sq - 34th St',
 '86 ST': '86th St',
 '125 ST': '125th St',
 'GRD CNTRL-42 ST': 'Grand Central - 42nd St',
 '23 ST': '23rd St',
 '42 ST-PORT AUTH': '42nd St - Port Authority Bus Term',
 '14 ST-UNION SQ': 'Union Sq - 14th St',
 'FLUSHING-MAIN': 'Flushing - Main St',
 '59 ST': '59th St',
 '96 ST': '96th St',
 'JKSN HT-ROOSVLT': 'Jackson Hts - Roosevelt Av',
 'FULTON ST': 'Fulton St',
 'TIMES SQ-42 ST': 'Times Sq - 42nd St',
 '59 ST COLUMBUS': '59th St - Columbus Circle',
 'CANAL ST': 'Canal St',
 '14 ST': '14th St',
 'CHURCH AV': 'Church Ave',
 'ATL AV-BARCLAY': "Atlantic Av - Barclay's Center",
 '72 ST': '72nd St',
 'PATH NEW WTC': 'World Trade Center',
 'JAMAICA CENTER': 'Jamaica Ctr - Parsons / Archer',
 '145 ST': '145th St',
 'JUNCTION BLVD': 'Junction Blvd',
 '47-50 STS ROCK': '47th-50th Sts - Rockefeller Ctr',
 '116 ST': '116th St',
 'KINGS HWY': 'Kings Hwy',
 '77 ST': '77th St',
 'DEKALB AV': 'DeKalb Ave',
 '28 ST': '28th St',
 '103 ST-CORONA': '103rd St - Corona Plaza',
 'CROWN HTS-UTICA': 'Crown Hts - Utica Ave',
 '103 ST': '103rd St',
 '8 AV': '8th Ave',
 'CHAMBERS ST': 'Chambers St',
 'GRAND ST': 'Grand St',
 'WOODHAVEN BLVD': 'Woodhaven Blvd',
 '72 ST-2 AVE': '72nd St',
 'W 4 ST-WASH SQ': 'W 4th St - Washington Sq (Lower)',
 '168 ST': '168th St',
 'FORDHAM RD': 'Fordham Rd',
 '161/YANKEE STAD': '161st St - Yankee Stadium',
 '50 ST': '50th St',
 'JAY ST-METROTEC': 'Jay St - MetroTech',
 'SUTPHIN-ARCHER': 'Sutphin Blvd - Archer Av',
 'FOREST HILLS 71': 'Forest Hills - 71st Av',
 'KEW GARDENS': 'Kew Gardens - Union Tpke',
 '3 AV-149 ST': '3rd Ave - 149th St',
 '90 ST-ELMHURST': '90th St - Elmhurst Av',
 'DELANCEY/ESSEX': 'Delancey St - Essex St',
 '167 ST': '167th St',
 '111 ST': '111th St',
 'LEXINGTON AV/53': 'Lexington Ave - 53rd St',
 'MYRTLE-WYCKOFF': 'Myrtle - Wyckoff Aves',
 'JAMAICA 179 ST': 'Jamaica - 179th St',
 '42 ST-BRYANT PK': '42nd St - Bryant Pk',
 'BOROUGH HALL': 'Borough Hall',
 'BEDFORD AV': 'Bedford Ave',
 '82 ST-JACKSON H': '82nd St - Jackson Hts',
 '33 ST': '33rd St',
 'NOSTRAND AV': 'Nostrand Ave',
 '57 ST-7 AV': '57th St',
 'GRAND-NEWTOWN': 'Grand Ave - Newtown',
 '61 ST WOODSIDE': 'Woodside - 61st St',
 '86 ST-2 AVE': 'Gravesend - 86th St',
 '36 ST': '36th St',
 'FLATBUSH AV-B.C': 'Brooklyn College - Flatbush Ave',
 'KINGSBRIDGE RD': 'Kingsbridge Rd',
 'WALL ST': 'Wall St',
 '79 ST': '79th St',
 'BAY PKWY': 'Bay Pky',
 '135 ST': '135th St',
 '68ST-HUNTER CO': '68th St - Hunter College',
 'FRANKLIN AV': 'Franklin Ave',
 'LEXINGTON AV/63': 'Lexington Ave - 63rd St',
 '170 ST': '170th St',
 'PARKCHESTER': 'Parkchester',
 '18 AV': '18th Ave',
 'CATHEDRAL PKWY': 'Cathedral Pkwy (110th St)',
 'CONEY IS-STILLW': 'Coney Island - Stillwell Av',
 'FT HAMILTON PKY': 'Ft Hamilton Pkwy',
 'BROADWAY': 'Broadway',
 '63 DR-REGO PARK': '63rd Dr - Rego Park',
 'SPRING ST': 'Spring St',
 'UTICA AV': 'Utica Ave',
 'AVENUE U': 'Ave U',
 'BOWLING GREEN': 'Bowling Green',
 'THIRTY THIRD ST': '33rd St',
 '34 ST-HUDSON YD': '34th St - Hudson Yards',
 'DYCKMAN ST': 'Dyckman St',
 'SHEEPSHEAD BAY': 'Sheepshead Bay',
 'ASTORIA DITMARS': 'Astoria - Ditmars Blvd',
 'HALSEY ST': 'Halsey St',
 'ELMHURST AV': 'Elmhurst Ave', 
 'FLUSHING AV': 'Flushing Ave', 
 "B'WAY-LAFAYETTE": 'Broadway - Lafayette St',
 'BRIGHTON BEACH': 'Brighton Beach',
 'STEINWAY ST': 'Steinway St', 
 'PROSPECT AV': 'Prospect Ave',
 'BEDFORD PK BLVD': 'Bedford Park Blvd',
 'GUN HILL RD': 'Gun Hill Rd',
 '137 ST CITY COL': '137th St - City College',
 'PELHAM PKWY': 'Pelham Pkwy'}